import React, { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

import { logStore } from '@/stores/LogStore';

import Link from 'next/link';

export default function About() {
  const { push } = useRouter();

  var { logs, fetchLogs } = logStore();

  const initial_page = parseInt(location.search.replace('?page=', ''));

  const [page, setPage] = useState(initial_page || 1);

  //set page in url
  useEffect(() => {
    push(`?page=${page}`);
  }, [page]);

  //get page from query ?page=1
  useEffect(() => {
    const page = parseInt(location.search.replace('?page=', ''));
    if (page) {
      console.log('page', page)
      setPage(page);
    }
  }, []);

  //fetch logs on load
  useEffect(() => {
    console.log(page)
    fetchLogs(page);
  }, []);

  return (
    <div>
      <div className="px-4 sm:px-6 lg:px-8 py-4">
        <div className="sm:flex sm:items-center">
          <div className="sm:flex-auto">
            <h1 className="text-base font-semibold leading-6 text-gray-900">Logs</h1>
            <p className="mt-2 text-sm text-gray-700">
              A list of all the logs that have been generated by the system.
            </p>
          </div>
          <div className="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
          </div>
        </div>
        <div className="mt-8 flow-root markdown-page markdown-content markdown-prompt-blockquote models">
          <div className="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div className="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
              <table className="min-w-full docs-models-toc">
                <thead>
                  <tr>
                    <th scope="col" className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">
                      Prompt
                    </th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                      Model
                    </th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                      Date
                    </th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                      Status
                    </th>
                    <th scope="col" className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">
                      Data
                    </th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {logs
                    .map((log) => (
                      <tr key={log.id}>
                        <td className="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
                          {log.model_id}
                        </td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{log.prompt_id}</td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{log.createdAt}</td>
                        <td
                          className={`whitespace-nowrap px-3 py-4 text-sm ${
                            log.status !== 200 ? 'bg-yellow-300' : '' // Add your yellow background class here
                          } text-gray-500`}
                        >
                          {log.status}
                        </td>
                        <td className="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{prompt.model}</td>
                      </tr>
                    ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
